/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.LocadoraVeiculo.Login;

import br.com.LocadoraVeiculo.Telas.Tela_Area_Cliente;
import javax.swing.JOptionPane;
import javax.swing.text.html.HTML;

/**
 *
 * @author edunativa
 */
public class LoginCliente extends javax.swing.JPanel {

    /**
     * Creates new form LoginCliente
     */
    public LoginCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPasswordCliente = new javax.swing.JPasswordField();
        bntEntrarCliente = new javax.swing.JButton();
        jTextUsuarioCliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelImag = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(400, 250));
        setPreferredSize(new java.awt.Dimension(400, 250));

        jPanel1.setLayout(null);

        jPasswordCliente.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jPasswordCliente.setMargin(new java.awt.Insets(0, 5, 0, 0));
        jPanel1.add(jPasswordCliente);
        jPasswordCliente.setBounds(150, 80, 189, 27);

        bntEntrarCliente.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        bntEntrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/LocadoraVeiculo/Icones/IconeEntrarCliente.png"))); // NOI18N
        bntEntrarCliente.setText("ENTRAR");
        bntEntrarCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bntEntrarCliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bntEntrarCliente.setMargin(new java.awt.Insets(0, 5, 0, 0));
        bntEntrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntEntrarClienteActionPerformed(evt);
            }
        });
        jPanel1.add(bntEntrarCliente);
        bntEntrarCliente.setBounds(60, 130, 156, 60);

        jTextUsuarioCliente.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jTextUsuarioCliente.setMargin(new java.awt.Insets(0, 5, 0, 0));
        jPanel1.add(jTextUsuarioCliente);
        jTextUsuarioCliente.setBounds(150, 40, 189, 25);

        jLabel1.setBackground(new java.awt.Color(238, 228, 217));
        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setText("Usuário:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 40, 77, 25);

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(254, 58, 58));
        jLabel3.setText("*Esqueci a minha Senha");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(150, 220, 118, 13);

        jLabel2.setBackground(new java.awt.Color(238, 228, 217));
        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setText("Senha:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 80, 67, 25);

        jLabelImag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/LocadoraVeiculo/Imagens/carros_Login.png"))); // NOI18N
        jLabelImag.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabelImag);
        jLabelImag.setBounds(0, 0, 400, 250);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bntEntrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEntrarClienteActionPerformed

        if(jTextUsuarioCliente.getText().equals("cliente") && jPasswordCliente.getText().equals("admin")){
            Tela_Area_Cliente telaCliente = new Tela_Area_Cliente();
            telaCliente.setVisible(true); //abrindo o tela Pricipal
            //Limpando os campos apos a abertura da Tela Area de Trabalho
            jTextUsuarioCliente.setText("");
            jPasswordCliente.setText("");

        }else{
            JOptionPane.showMessageDialog(null, "Usuário ou Senha Incorreta!");
            //Limpando os campos apos aparecer a messagem de Erro;
            jTextUsuarioCliente.setText("");
            jPasswordCliente.setText("");
        }
    }//GEN-LAST:event_bntEntrarClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntEntrarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelImag;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordCliente;
    private javax.swing.JTextField jTextUsuarioCliente;
    // End of variables declaration//GEN-END:variables
}
