
package br.com.LocadoraVeiculo.Login;

import br.com.LocadoraVeiculo.ConexaoBD.ConexaoBD;
import br.com.LocadoraVeiculo.Telas.Tela_Area_de_Trab;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author edunativa
 */
public class LoginGerente extends javax.swing.JPanel {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public void logar(){
        String SQL = "select * from Administrador where login= ? and senha= ?";
        
        try {
            
            pst = conexao.prepareStatement(SQL);
            pst.setString(1, jTextUsuarioGerente.getText());
            pst.setString(2, jPasswordGerente.getText());
            //A linha abaixo executa a consulta acima no Banco de Dados;
            rs = pst.executeQuery();
            
            if(rs.next()){
              Tela_Area_de_Trab AreaTrab = new Tela_Area_de_Trab();
                AreaTrab.setVisible(true); //abrindo o tela Pricipal
                
                                
            }else{
                
                JOptionPane.showMessageDialog(null, "Usuário ou Senha Incorreta!");
                jTextUsuarioGerente.setText("");
                jPasswordGerente.setText("");
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Um Erro Aconteceu!\nNão foi possível Logar:  "+e);
        
        }
        
    }
    
    /**
     * Creates new form LoginGerente
     */
    public LoginGerente() {
        initComponents();
        conexao = ConexaoBD.conector();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelImagemFundo = new javax.swing.JPanel();
        bntEntrarGerente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextUsuarioGerente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPasswordGerente = new javax.swing.JPasswordField();
        jTxtEsqueceu = new javax.swing.JLabel();
        jImgemFundo = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(400, 250));

        jPanelImagemFundo.setPreferredSize(new java.awt.Dimension(399, 249));
        jPanelImagemFundo.setLayout(null);

        bntEntrarGerente.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        bntEntrarGerente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/LocadoraVeiculo/Icones/IconeEntrarGerente.png"))); // NOI18N
        bntEntrarGerente.setText("ENTRAR");
        bntEntrarGerente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bntEntrarGerente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bntEntrarGerente.setMargin(new java.awt.Insets(0, 5, 0, 0));
        bntEntrarGerente.setMaximumSize(new java.awt.Dimension(156, 60));
        bntEntrarGerente.setMinimumSize(new java.awt.Dimension(156, 60));
        bntEntrarGerente.setPreferredSize(new java.awt.Dimension(125, 60));
        bntEntrarGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntEntrarGerenteActionPerformed(evt);
            }
        });
        jPanelImagemFundo.add(bntEntrarGerente);
        bntEntrarGerente.setBounds(60, 130, 156, 60);

        jLabel1.setBackground(new java.awt.Color(238, 228, 217));
        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setText("Usuário:");
        jPanelImagemFundo.add(jLabel1);
        jLabel1.setBounds(60, 40, 77, 25);

        jTextUsuarioGerente.setColumns(15);
        jTextUsuarioGerente.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jTextUsuarioGerente.setMargin(new java.awt.Insets(0, 5, 0, 0));
        jPanelImagemFundo.add(jTextUsuarioGerente);
        jTextUsuarioGerente.setBounds(150, 40, 189, 29);

        jLabel2.setBackground(new java.awt.Color(238, 228, 217));
        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setText("Senha:");
        jPanelImagemFundo.add(jLabel2);
        jLabel2.setBounds(70, 80, 67, 25);

        jPasswordGerente.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jPasswordGerente.setMargin(new java.awt.Insets(0, 5, 0, 0));
        jPasswordGerente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordGerenteKeyPressed(evt);
            }
        });
        jPanelImagemFundo.add(jPasswordGerente);
        jPasswordGerente.setBounds(150, 80, 189, 29);

        jTxtEsqueceu.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        jTxtEsqueceu.setForeground(new java.awt.Color(254, 58, 58));
        jTxtEsqueceu.setText("*Esqueci a minha Senha");
        jTxtEsqueceu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTxtEsqueceuMousePressed(evt);
            }
        });
        jPanelImagemFundo.add(jTxtEsqueceu);
        jTxtEsqueceu.setBounds(150, 220, 118, 13);

        jImgemFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/LocadoraVeiculo/Imagens/carros_Login.png"))); // NOI18N
        jImgemFundo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jImgemFundo.setMaximumSize(new java.awt.Dimension(400, 250));
        jImgemFundo.setMinimumSize(new java.awt.Dimension(400, 250));
        jImgemFundo.setPreferredSize(new java.awt.Dimension(400, 250));
        jPanelImagemFundo.add(jImgemFundo);
        jImgemFundo.setBounds(0, 0, 400, 250);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelImagemFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelImagemFundo, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bntEntrarGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEntrarGerenteActionPerformed
       logar();
        
    }//GEN-LAST:event_bntEntrarGerenteActionPerformed

    private void jTxtEsqueceuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtEsqueceuMousePressed
        String titulo = "Recuperar Senha";
        String menssagem = "Caso você tanha esquecido a sua senha ou login\nNão têm problema, clique em umas das opções abaixo!";
         
        int opcao = JOptionPane.showConfirmDialog(null,menssagem, titulo ,JOptionPane.YES_OPTION);
         
         if(opcao == JOptionPane.YES_OPTION){
             System.out.println("Você Conseguiu!!!");
             
         }
    }//GEN-LAST:event_jTxtEsqueceuMousePressed

    //Metodo irá fazer o usuário logar ao preencher login e senha e apertar ENTER
    private void jPasswordGerenteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordGerenteKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){ //Apos Digitar a Senha no campo aperte ENTER
            logar(); //Loga No Sistema procurando no Banco de Dados!
        }
    }//GEN-LAST:event_jPasswordGerenteKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntEntrarGerente;
    private javax.swing.JLabel jImgemFundo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelImagemFundo;
    private javax.swing.JPasswordField jPasswordGerente;
    private javax.swing.JTextField jTextUsuarioGerente;
    private javax.swing.JLabel jTxtEsqueceu;
    // End of variables declaration//GEN-END:variables

   
}
