/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.LocadoraVeiculo.Login;

import br.com.LocadoraVeiculo.Telas.Tela_Area_Cliente;
import br.com.LocadoraVeiculo.ConexaoBD.ConexaoBD;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author edunativa
 */
public class LoginCliente extends javax.swing.JPanel {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public void logar() {
        String SQL = "select * from Usuario where nomeLogin= ? and senhaLogin= ?";

        try {

            pst = conexao.prepareStatement(SQL);
            pst.setString(1, jTextUsuarioCliente.getText());
            pst.setString(2, jPasswordCliente.getText());
            //A linha abaixo executa a consulta acima no Banco de Dados;
            rs = pst.executeQuery();

            if (rs.next()) {
                Tela_Area_Cliente areaCli = new Tela_Area_Cliente();
                areaCli.setVisible(true); //abrindo o tela Pricipal
               
                jTextUsuarioCliente.setText(null);
                jPasswordCliente.setText(null);

            } else {

                JOptionPane.showMessageDialog(null, "Usuário ou Senha Incorreta!");
                jTextUsuarioCliente.setText(null);
                jPasswordCliente.setText(null);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Um Erro Aconteceu!\nNão foi possível Logar:  " + e);

        }

    }

    /**
     * Creates new form LoginCliente
     */
    public LoginCliente() {
        initComponents();
        conexao = ConexaoBD.conector();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPasswordCliente = new javax.swing.JPasswordField();
        bntEntrarCliente = new javax.swing.JButton();
        jTextUsuarioCliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jblRecuperarSenha = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelImag = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(400, 250));
        setPreferredSize(new java.awt.Dimension(400, 250));

        jPanel1.setLayout(null);

        jPasswordCliente.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jPasswordCliente.setMargin(new java.awt.Insets(0, 5, 0, 0));
        jPasswordCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordClienteKeyPressed(evt);
            }
        });
        jPanel1.add(jPasswordCliente);
        jPasswordCliente.setBounds(150, 80, 189, 29);

        bntEntrarCliente.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        bntEntrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/LocadoraVeiculo/Icones/IconeEntrarCliente.png"))); // NOI18N
        bntEntrarCliente.setText("ENTRAR");
        bntEntrarCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bntEntrarCliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bntEntrarCliente.setMargin(new java.awt.Insets(0, 5, 0, 0));
        bntEntrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntEntrarClienteActionPerformed(evt);
            }
        });
        jPanel1.add(bntEntrarCliente);
        bntEntrarCliente.setBounds(60, 130, 156, 60);

        jTextUsuarioCliente.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jTextUsuarioCliente.setMargin(new java.awt.Insets(0, 5, 0, 0));
        jPanel1.add(jTextUsuarioCliente);
        jTextUsuarioCliente.setBounds(150, 40, 189, 29);

        jLabel1.setBackground(new java.awt.Color(238, 228, 217));
        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setText("Usuário:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 40, 77, 25);

        jblRecuperarSenha.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        jblRecuperarSenha.setForeground(new java.awt.Color(254, 58, 58));
        jblRecuperarSenha.setText("*Esqueci a minha Senha");
        jblRecuperarSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jblRecuperarSenhaMousePressed(evt);
            }
        });
        jPanel1.add(jblRecuperarSenha);
        jblRecuperarSenha.setBounds(150, 220, 118, 13);

        jLabel2.setBackground(new java.awt.Color(238, 228, 217));
        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setText("Senha:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 80, 67, 25);

        jLabelImag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/LocadoraVeiculo/Imagens/carros_Login.png"))); // NOI18N
        jLabelImag.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabelImag);
        jLabelImag.setBounds(0, 0, 400, 250);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bntEntrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEntrarClienteActionPerformed
        logar();
    }//GEN-LAST:event_bntEntrarClienteActionPerformed

    //Metodo para o Usuário entrar no Sistema apos digitar a senha apertar a tecla ENTER
    private void jPasswordClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordClienteKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) { //Se aperta a tecla Enter irá tentar Logar
            logar();
        }
    }//GEN-LAST:event_jPasswordClienteKeyPressed

    private void jblRecuperarSenhaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblRecuperarSenhaMousePressed
        
        String titulo = "Recuperar Senha";
        String menssagem = "Sr Cliente. Caso queira cadastrar uma nova senha\nNão têm problema, Clique em SIM!";
         
        int opcao = JOptionPane.showConfirmDialog(null,menssagem, titulo ,JOptionPane.YES_OPTION);
         
         if(opcao == JOptionPane.YES_OPTION){
             System.out.println("Parabéns Você Disse SIM para Cadastrar uma Novo Login e Senha!!!");
             RecuperarSenha g = new RecuperarSenha();
             g.setVisible(true);
         }
        
    }//GEN-LAST:event_jblRecuperarSenhaMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntEntrarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelImag;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordCliente;
    private javax.swing.JTextField jTextUsuarioCliente;
    private javax.swing.JLabel jblRecuperarSenha;
    // End of variables declaration//GEN-END:variables
}
