/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.LocadoraVeiculo.Login;

import br.com.LocadoraVeiculo.ConexaoBD.ConexaoBD;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author edunativa
 */
public class RecuperarSenha extends javax.swing.JFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form RecuperarSenhaa
     */
    public RecuperarSenha() {
        initComponents();
        conexao = ConexaoBD.conector();
    }

    //Metodo para Consultar o CPF do Cliente para poder o mesmo poder fazer uma nova senha;
    public void Consultar() {
        String sql = "select * from Usuario where CPF= ?"; //Pesquisa no campo CPF da tabela do Banco de Dados;

        try {

            pst = conexao.prepareStatement(sql);
            pst.setString(1, jFormattedCPF.getText());

            //A linha abaixo executa a consulta acima no Banco de Dados;
            rs = pst.executeQuery();

            if (rs.next()) {
                //caso encontre o CPF no Banco de Dados irá habilitar o iconeStatus;
                //mostrar o nomeLogin do Usuario
                jTextFieldNomeUsuario.setText(rs.getString(2)); // 2 é o a posição na Tabela ou seja nomeLogin
                iconeStatus.setEnabled(true);
                jTextFieldNomeUsuario.setEnabled(true);
                jPasswordNovaSenha.setEnabled(true);
                jPasswordConfirSenha.setEnabled(true);

            } else {

                JOptionPane.showMessageDialog(null, "CPF não Encontrado!");

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Um Erro Aconteceu!\nNão Valor Inválido:  " + e);

        }
    }

    //Metodo para Alterar o senha do Cliente no Banco de dados;
    public void AlterarSenha() {
        String sql = "update Usuario set senhaLogin=? where CPF=?";
        try {
            pst = conexao.prepareStatement(sql);
           
            if (jPasswordNovaSenha.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Falta Preenche os Campos Obrigatórios!!");

                

            } else {
                         
                
                
                pst.setString(1, jPasswordNovaSenha.getText());
                pst.setString(2, jFormattedCPF.getText());
                
                
                int adicionar = pst.executeUpdate();
                
                if (adicionar > 0) {
                    JOptionPane.showMessageDialog(null, "Nome e Senha de Usuário\nAlterada com Sucesso!!!");
                    jTextFieldNomeUsuario.setText(null);
                    jPasswordNovaSenha.setText(null);
                    jPasswordConfirSenha.setText(null);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    

    public void AlterarSenhaG() {
        String sql = "update Administrador set login=?, senha=?";
        try {
            pst = conexao.prepareStatement(sql);
           
            if (jPasswordNovaSenha.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Falta Preenche os Campos Obrigatórios!!");

                

            } else {
                         
                
                pst.setString(1, jTextFieldNomeUsuario.getText());
                pst.setString(2, jPasswordNovaSenha.getText());
                
                int adicionar = pst.executeUpdate();
                
                if (adicionar > 0) {
                    JOptionPane.showMessageDialog(null, "Nome e Senha de Usuário\nAlterada com Sucesso!!!");
                    jTextFieldNomeUsuario.setText(null);
                    jPasswordNovaSenha.setText(null);
                    jPasswordConfirSenha.setText(null);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jFormattedCPF = new javax.swing.JFormattedTextField();
        btnPesq = new javax.swing.JButton();
        iconeStatus = new javax.swing.JLabel();
        jPanelNovaSenha = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPasswordConfirSenha = new javax.swing.JPasswordField();
        jPasswordNovaSenha = new javax.swing.JPasswordField();
        iconeSenhaOk = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNomeUsuario = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Recuperar Senha");
        setMaximumSize(new java.awt.Dimension(500, 340));
        setName("Tela de Recuperacao"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Entre com o seu CPF no campo abaixo para Criar um novo acesso.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 18, -1, 37));

        jLabel4.setText("Seu CPF:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 88, 60, -1));

        try {
            jFormattedCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedCPF.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        getContentPane().add(jFormattedCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 78, 176, 36));

        btnPesq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/LocadoraVeiculo/Icones/IconePesquisa.png"))); // NOI18N
        btnPesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesqActionPerformed(evt);
            }
        });
        getContentPane().add(btnPesq, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 68, 60, -1));

        iconeStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/LocadoraVeiculo/Icones/iconeSIM.png"))); // NOI18N
        iconeStatus.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/LocadoraVeiculo/Icones/IconeNao.png"))); // NOI18N
        iconeStatus.setEnabled(false);
        iconeStatus.setOpaque(true);
        getContentPane().add(iconeStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 78, 30, 40));

        jPanelNovaSenha.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.gray));
        jPanelNovaSenha.setEnabled(false);

        jLabel2.setText("Nova Senha:");

        jLabel3.setText("Confirmar Senha:");

        jPasswordConfirSenha.setEnabled(false);
        jPasswordConfirSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordConfirSenhaKeyPressed(evt);
            }
        });

        jPasswordNovaSenha.setEnabled(false);

        iconeSenhaOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/LocadoraVeiculo/Icones/iconeSIM.png"))); // NOI18N
        iconeSenhaOk.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/LocadoraVeiculo/Icones/IconeNao.png"))); // NOI18N
        iconeSenhaOk.setEnabled(false);
        iconeSenhaOk.setOpaque(true);

        jLabel5.setText("Nome de Usuário:");

        jTextFieldNomeUsuario.setEnabled(false);

        javax.swing.GroupLayout jPanelNovaSenhaLayout = new javax.swing.GroupLayout(jPanelNovaSenha);
        jPanelNovaSenha.setLayout(jPanelNovaSenhaLayout);
        jPanelNovaSenhaLayout.setHorizontalGroup(
            jPanelNovaSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNovaSenhaLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanelNovaSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelNovaSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelNovaSenhaLayout.createSequentialGroup()
                        .addComponent(jPasswordConfirSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(iconeSenhaOk))
                    .addGroup(jPanelNovaSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextFieldNomeUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                        .addComponent(jPasswordNovaSenha, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanelNovaSenhaLayout.setVerticalGroup(
            jPanelNovaSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNovaSenhaLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(jPanelNovaSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelNovaSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelNovaSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelNovaSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jPasswordConfirSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(iconeSenhaOk, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        getContentPane().add(jPanelNovaSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 136, -1, -1));

        btnSalvar.setText("SALVAR");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 288, 113, 43));

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 288, 113, 43));

        setSize(new java.awt.Dimension(505, 370));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesqActionPerformed
        Consultar();
    }//GEN-LAST:event_btnPesqActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        jFormattedCPF.setText(null);
        jTextFieldNomeUsuario.setText(null);
        jPasswordNovaSenha.setText(null);
        jPasswordConfirSenha.setText(null);
        iconeStatus.setEnabled(false);
        iconeSenhaOk.setEnabled(false);

    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        AlterarSenha();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void jPasswordConfirSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordConfirSenhaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            if (jPasswordNovaSenha.getText().equals(jPasswordConfirSenha.getText())) { //verifica se a nova senha e a senha de confirmação são iguais;
                iconeSenhaOk.setEnabled(true); // caso as senhas forem iguais ativa o icone e passa o valor para o banco de dados;
                btnSalvar.setEnabled(true); // fazer o Botão salvar aparecer;
            } else {
                iconeSenhaOk.setEnabled(false);
            }
        }
    }//GEN-LAST:event_jPasswordConfirSenhaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecuperarSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecuperarSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecuperarSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecuperarSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecuperarSenha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnPesq;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel iconeSenhaOk;
    private javax.swing.JLabel iconeStatus;
    private javax.swing.JFormattedTextField jFormattedCPF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanelNovaSenha;
    private javax.swing.JPasswordField jPasswordConfirSenha;
    private javax.swing.JPasswordField jPasswordNovaSenha;
    private javax.swing.JTextField jTextFieldNomeUsuario;
    // End of variables declaration//GEN-END:variables
}
