/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.LocadoraVeiculo.Telas;

//import java.text.SimpleDateFormat;
import br.com.LocadoraVeiculo.Telas.Cadastros.Tela_CadFuncionario;
import br.com.LocadoraVeiculo.Telas.Cadastros.Tela_CadVeiculo;
import br.com.LocadoraVeiculo.Telas.Cadastros.Tela_CadastroCliente;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.time.format.FormatStyle;

/**
 *
 * @author edunativa
 */
public class Tela_Area_de_Trab extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Area_de_Trab
     */
    public Tela_Area_de_Trab() {
            
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Icones = new javax.swing.JPanel();
        btnCadCliente = new javax.swing.JButton();
        btnCadVeiculos = new javax.swing.JButton();
        btnRelatorioClientes = new javax.swing.JButton();
        btnRelatorioVeiculos = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLData = new javax.swing.JLabel();
        DesktopDoSistema = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastros_Clientes = new javax.swing.JMenu();
        jMenuItemClientes = new javax.swing.JMenuItem();
        jMenuItemFuncionario = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuRelatorios = new javax.swing.JMenu();
        jMenuItemPesqCliente = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setTitle("Sistema de Locação de Veiculos");
        setExtendedState(6);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("AreaTrabalho"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel_Icones.setPreferredSize(new java.awt.Dimension(800, 60));

        btnCadCliente.setBackground(java.awt.Color.white);
        btnCadCliente.setForeground(java.awt.Color.darkGray);
        btnCadCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/LocadoraVeiculo/Icones/Icone 54x54 cadastro Laranja.png"))); // NOI18N
        btnCadCliente.setToolTipText("Cad. Cliente");
        btnCadCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCadCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadCliente.setMaximumSize(new java.awt.Dimension(54, 54));
        btnCadCliente.setMinimumSize(new java.awt.Dimension(54, 54));
        btnCadCliente.setPreferredSize(new java.awt.Dimension(54, 54));
        btnCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadClienteActionPerformed(evt);
            }
        });

        btnCadVeiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/LocadoraVeiculo/Icones/Icone 54x54 cadastro cliente.png"))); // NOI18N
        btnCadVeiculos.setToolTipText("Cad. Veículo");
        btnCadVeiculos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCadVeiculos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadVeiculos.setMaximumSize(new java.awt.Dimension(54, 54));
        btnCadVeiculos.setMinimumSize(new java.awt.Dimension(54, 54));
        btnCadVeiculos.setPreferredSize(new java.awt.Dimension(54, 54));
        btnCadVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadVeiculosActionPerformed(evt);
            }
        });

        btnRelatorioClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/LocadoraVeiculo/Icones/Icone 54x54 relatorioCliente.png"))); // NOI18N
        btnRelatorioClientes.setToolTipText("Relatório Cliente");
        btnRelatorioClientes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRelatorioClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRelatorioClientes.setMaximumSize(new java.awt.Dimension(54, 54));
        btnRelatorioClientes.setMinimumSize(new java.awt.Dimension(54, 54));
        btnRelatorioClientes.setPreferredSize(new java.awt.Dimension(54, 54));
        btnRelatorioClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioClientesActionPerformed(evt);
            }
        });

        btnRelatorioVeiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/LocadoraVeiculo/Icones/Icone 54x54 relatorioVeiculo.png"))); // NOI18N
        btnRelatorioVeiculos.setToolTipText("Relatório Veículo");
        btnRelatorioVeiculos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRelatorioVeiculos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRelatorioVeiculos.setMaximumSize(new java.awt.Dimension(54, 54));
        btnRelatorioVeiculos.setMinimumSize(new java.awt.Dimension(54, 54));
        btnRelatorioVeiculos.setPreferredSize(new java.awt.Dimension(54, 54));
        btnRelatorioVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioVeiculosActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/LocadoraVeiculo/Icones/Icone 54x54 Veiculos Laranja.png"))); // NOI18N
        jButton1.setToolTipText("Tabela Veiculos");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setMaximumSize(new java.awt.Dimension(54, 54));
        jButton1.setMinimumSize(new java.awt.Dimension(54, 54));
        jButton1.setPreferredSize(new java.awt.Dimension(54, 54));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLData.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLData.setForeground(new java.awt.Color(204, 0, 0));
        jLData.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLData.setLabelFor(jLData);
        jLData.setText("Data:");

        javax.swing.GroupLayout jPanel_IconesLayout = new javax.swing.GroupLayout(jPanel_Icones);
        jPanel_Icones.setLayout(jPanel_IconesLayout);
        jPanel_IconesLayout.setHorizontalGroup(
            jPanel_IconesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_IconesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCadVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRelatorioClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRelatorioVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(307, 307, 307)
                .addComponent(jLData, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(316, 316, 316))
        );
        jPanel_IconesLayout.setVerticalGroup(
            jPanel_IconesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_IconesLayout.createSequentialGroup()
                .addGroup(jPanel_IconesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLData, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_IconesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel_IconesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCadCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCadVeiculos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRelatorioClientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRelatorioVeiculos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        DesktopDoSistema.setMaximumSize(new java.awt.Dimension(1024, 700));
        DesktopDoSistema.setMinimumSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout DesktopDoSistemaLayout = new javax.swing.GroupLayout(DesktopDoSistema);
        DesktopDoSistema.setLayout(DesktopDoSistemaLayout);
        DesktopDoSistemaLayout.setHorizontalGroup(
            DesktopDoSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        DesktopDoSistemaLayout.setVerticalGroup(
            DesktopDoSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 729, Short.MAX_VALUE)
        );

        jMenuBar1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        jMenuCadastros_Clientes.setForeground(new java.awt.Color(0, 0, 0));
        jMenuCadastros_Clientes.setText("Cadastrar");
        jMenuCadastros_Clientes.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        jMenuItemClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemClientes.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jMenuItemClientes.setText("Cliente");
        jMenuCadastros_Clientes.add(jMenuItemClientes);

        jMenuItemFuncionario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemFuncionario.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jMenuItemFuncionario.setText("Funcionário");
        jMenuItemFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFuncionarioActionPerformed(evt);
            }
        });
        jMenuCadastros_Clientes.add(jMenuItemFuncionario);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jMenuItem1.setText("Veículo");
        jMenuCadastros_Clientes.add(jMenuItem1);

        jMenuBar1.add(jMenuCadastros_Clientes);

        jMenuRelatorios.setText("Relatórios");
        jMenuRelatorios.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        jMenuItemPesqCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemPesqCliente.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jMenuItemPesqCliente.setText("Pesquisar Cliente");
        jMenuItemPesqCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPesqClienteActionPerformed(evt);
            }
        });
        jMenuRelatorios.add(jMenuItemPesqCliente);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jMenuItem2.setText("Pesquisar Veículo");
        jMenuRelatorios.add(jMenuItem2);

        jMenuBar1.add(jMenuRelatorios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopDoSistema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_Icones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1283, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_Icones, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DesktopDoSistema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       //Para Mostrar a Data do Sistema
       
       //Nas Versões Anteriores do Java
       /* Date dataNoSistema = new Date();
       SimpleDateFormat formatoData = new SimpleDateFormat("dd/MM/yyyy");
       jLData.setText(formatoData.format(dataNoSistema));
       */  
       
        LocalDate dataAtual = LocalDate.now();
        DateTimeFormatter formatoData;
        formatoData = DateTimeFormatter.ofLocalizedDate(FormatStyle.LONG);
        jLData.setText(formatoData.format(dataAtual));
        
       //Para Mostrar a Hora do Sitema;
       /*LocalTime tempo = LocalTime.now();
       DateTimeFormatter formatoHora;
       formatoHora = DateTimeFormatter.ofLocalizedTime(FormatStyle.SHORT);*/
        
        
        //Nas Versões Anterios do Java;
        /*Timer tempo = new Timer(1000, new hora());
        tempo.start();*/
       
       
              
    }//GEN-LAST:event_formWindowOpened

    private void btnCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadClienteActionPerformed
            Tela_CadastroCliente Cadcliente = new Tela_CadastroCliente();
            DesktopDoSistema.add(Cadcliente);
            if(!Cadcliente.isVisible()){
                 Cadcliente.setVisible(true);
                 btnCadCliente.setEnabled(false);
                 btnCadVeiculos.setEnabled(true);
                 btnRelatorioClientes.setEnabled(true);
                 btnRelatorioVeiculos.setEnabled(true);
            }else{
                Cadcliente.dispose();
               
            }
                
               
            
            
            
    }//GEN-LAST:event_btnCadClienteActionPerformed

    private void btnCadVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadVeiculosActionPerformed
        Tela_CadVeiculo CadVeiculo = new Tela_CadVeiculo();
            DesktopDoSistema.add(CadVeiculo);
            if(!CadVeiculo.isVisible()){
                 CadVeiculo.setVisible(true);
                 btnCadVeiculos.setEnabled(false);
                 btnCadCliente.setEnabled(true);
                 btnRelatorioClientes.setEnabled(true);
                 btnRelatorioVeiculos.setEnabled(true);
                
            }else{
                CadVeiculo.dispose();
                
            }
                
    }//GEN-LAST:event_btnCadVeiculosActionPerformed

    private void jMenuItemFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFuncionarioActionPerformed
                 Tela_CadFuncionario CadFunc = new Tela_CadFuncionario();
                 DesktopDoSistema.add(CadFunc);
                 if(!CadFunc.isVisible()){
                     CadFunc.setVisible(true);
                        btnCadCliente.setEnabled(true);
                        btnCadVeiculos.setEnabled(true);
                        btnRelatorioClientes.setEnabled(true);
                        btnRelatorioVeiculos.setEnabled(true);
                 }else{
                     CadFunc.dispose();
                 }
        
                 
    }//GEN-LAST:event_jMenuItemFuncionarioActionPerformed

    private void btnRelatorioClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioClientesActionPerformed
       Tela_RelatorioCliente RelatorioCliente;
        RelatorioCliente = new Tela_RelatorioCliente();
        DesktopDoSistema.add(RelatorioCliente);
        if(RelatorioCliente.isVisible()){
            RelatorioCliente.setVisible(true);
            btnCadCliente.setEnabled(true);
            btnCadVeiculos.setEnabled(true);
            btnRelatorioClientes.setEnabled(false);
            btnRelatorioVeiculos.setEnabled(true);
            
        }else{
            RelatorioCliente.dispose();
        }
    }//GEN-LAST:event_btnRelatorioClientesActionPerformed

    private void btnRelatorioVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioVeiculosActionPerformed
        Tela_RelatorioVeiculo RelatorioVeiculo;
        RelatorioVeiculo = new Tela_RelatorioVeiculo();
        DesktopDoSistema.add(RelatorioVeiculo);
        if(RelatorioVeiculo.isVisible()){
            RelatorioVeiculo.setVisible(true);
            btnCadCliente.setEnabled(true);
            btnCadVeiculos.setEnabled(true);
            btnRelatorioClientes.setEnabled(true);
            btnRelatorioVeiculos.setEnabled(false);
        }
    }//GEN-LAST:event_btnRelatorioVeiculosActionPerformed

    private void jMenuItemPesqClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPesqClienteActionPerformed
        Tela_RelatorioCliente RelatorioCliente;
        RelatorioCliente = new Tela_RelatorioCliente();
        DesktopDoSistema.add(RelatorioCliente);
        if(RelatorioCliente.isVisible()){
            RelatorioCliente.setVisible(true);
            btnCadCliente.setEnabled(true);
            btnCadVeiculos.setEnabled(true);
            btnRelatorioClientes.setEnabled(true);
            btnRelatorioVeiculos.setEnabled(true);
            
        }
    }//GEN-LAST:event_jMenuItemPesqClienteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Tela_Area_Cliente telaCliente = new Tela_Area_Cliente();
        telaCliente.setVisible(true);
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Area_de_Trab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Area_de_Trab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Area_de_Trab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Area_de_Trab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Area_de_Trab().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopDoSistema;
    private javax.swing.JButton btnCadCliente;
    private javax.swing.JButton btnCadVeiculos;
    private javax.swing.JButton btnRelatorioClientes;
    private javax.swing.JButton btnRelatorioVeiculos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLData;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastros_Clientes;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemClientes;
    private javax.swing.JMenuItem jMenuItemFuncionario;
    private javax.swing.JMenuItem jMenuItemPesqCliente;
    private javax.swing.JMenu jMenuRelatorios;
    private javax.swing.JPanel jPanel_Icones;
    // End of variables declaration//GEN-END:variables

    //Para se Mostar a Hora nas Versões Anteriores do Java;
    /* public class hora implements ActionListener {
    @Override
    public  void actionPerformed(ActionEvent e){
    Calendar now = Calendar.getInstance();
    jLHora.setText(String.format("%1$tH:%1$tM", now));
    }
    }*/


}
