
package Telas;

import ClassesDAO.Gerente;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author edunativa
 */
public class LoginGerente extends javax.swing.JPanel {

    /**
     * Creates new form LoginGerente
     */
    public LoginGerente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextUsuarioGerente = new javax.swing.JTextField();
        jPasswordGerente = new javax.swing.JPasswordField();
        jTxtEsqueceu = new javax.swing.JLabel();
        bntEntrarGerente = new javax.swing.JButton();

        jLabel1.setBackground(new java.awt.Color(238, 228, 217));
        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setText("Usuário:");

        jLabel2.setBackground(new java.awt.Color(238, 228, 217));
        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setText("Senha:");

        jTextUsuarioGerente.setColumns(15);
        jTextUsuarioGerente.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        jPasswordGerente.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        jTxtEsqueceu.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        jTxtEsqueceu.setForeground(new java.awt.Color(254, 58, 58));
        jTxtEsqueceu.setText("*Esqueci a minha Senha");
        jTxtEsqueceu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTxtEsqueceuMousePressed(evt);
            }
        });

        bntEntrarGerente.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        bntEntrarGerente.setText("ENTRAR");
        bntEntrarGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntEntrarGerenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextUsuarioGerente, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addComponent(jPasswordGerente)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(bntEntrarGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTxtEsqueceu, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextUsuarioGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtEsqueceu)
                .addGap(28, 28, 28)
                .addComponent(bntEntrarGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bntEntrarGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEntrarGerenteActionPerformed
       
         if(jTextUsuarioGerente.getText().equals("gerente") && jPasswordGerente.getText().equals("123")){
            Tela_Area_de_Trab tela1 = new Tela_Area_de_Trab();
            tela1.setVisible(true); //abrindo o tela Pricipal
            //Limpando os campos apos a abertura da Tela Area de Trabalho
            jTextUsuarioGerente.setText("");
            jPasswordGerente.setText("");
         
        
         }else{
             JOptionPane.showMessageDialog(null, "Usuário ou Senha Incorreta!");
             //Limpando os campos apos aparecer a messagem de Erro;
            jTextUsuarioGerente.setText("");
            jPasswordGerente.setText("");
         }
    }//GEN-LAST:event_bntEntrarGerenteActionPerformed

    private void jTxtEsqueceuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtEsqueceuMousePressed
        String titulo = "Recuperar Senha";
        String menssagem = "Caso você tanha esquecido a sua senha ou login\nNão têm problema, clique em umas das opções abaixo!";
         
        int opcao = JOptionPane.showConfirmDialog(null,menssagem, titulo ,JOptionPane.YES_NO_OPTION);
         
         if(opcao == JOptionPane.YES_OPTION){
             JOptionPane.showMessageDialog(null, "Você Conseguiu!");
         }
    }//GEN-LAST:event_jTxtEsqueceuMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntEntrarGerente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordGerente;
    private javax.swing.JTextField jTextUsuarioGerente;
    private javax.swing.JLabel jTxtEsqueceu;
    // End of variables declaration//GEN-END:variables

   
}
