/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import java.awt.BorderLayout;

/**
 *
 * @author edunativa
 */
public class Tela_Login extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Login
     */
    public Tela_Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btn_EntrarCliente = new javax.swing.JButton();
        btn_EntrarGerente = new javax.swing.JButton();
        jPanelLogin = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtLogin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login do Sistema de Locação de Veículo");
        setMaximumSize(new java.awt.Dimension(600, 400));
        setMinimumSize(null);
        setName("TelaLogin"); // NOI18N
        setResizable(false);

        jPanel2.setLayout(null);

        btn_EntrarCliente.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btn_EntrarCliente.setText("CLIENTE");
        btn_EntrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EntrarClienteActionPerformed(evt);
            }
        });
        jPanel2.add(btn_EntrarCliente);
        btn_EntrarCliente.setBounds(440, 250, 150, 90);

        btn_EntrarGerente.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btn_EntrarGerente.setText("GERENTE");
        btn_EntrarGerente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_EntrarGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EntrarGerenteActionPerformed(evt);
            }
        });
        jPanel2.add(btn_EntrarGerente);
        btn_EntrarGerente.setBounds(440, 140, 150, 90);

        jPanelLogin.setBackground(new java.awt.Color(238, 228, 217));
        jPanelLogin.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelLogin.setMinimumSize(new java.awt.Dimension(350, 200));
        jPanelLogin.setPreferredSize(new java.awt.Dimension(350, 200));

        javax.swing.GroupLayout jPanelLoginLayout = new javax.swing.GroupLayout(jPanelLogin);
        jPanelLogin.setLayout(jPanelLoginLayout);
        jPanelLoginLayout.setHorizontalGroup(
            jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
        );
        jPanelLoginLayout.setVerticalGroup(
            jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 246, Short.MAX_VALUE)
        );

        jPanel2.add(jPanelLogin);
        jPanelLogin.setBounds(20, 110, 410, 250);

        jLabel3.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(1, 1, 1));
        jLabel3.setText("Sistema de Locação de Veículo");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(90, 10, 430, 50);

        txtLogin.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jPanel2.add(txtLogin);
        txtLogin.setBounds(20, 80, 290, 30);

        jLabel1.setBackground(new java.awt.Color(182, 181, 179));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundoLogin.jpg"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_EntrarGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EntrarGerenteActionPerformed
       
        txtLogin.setText("Logar com Gerente");
        
        LoginGerente  PLoginG = new LoginGerente();
        PLoginG.setSize(400, 250); //Dimencional a JPanel para o tamanho desejado
        PLoginG.setLocation(0, 0);
        
        jPanelLogin.removeAll();
        jPanelLogin.add(PLoginG, BorderLayout.CENTER);
        jPanelLogin.revalidate();
    }//GEN-LAST:event_btn_EntrarGerenteActionPerformed

    private void btn_EntrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EntrarClienteActionPerformed
        
         txtLogin.setText("Logar com Cliente");
        
        LoginCliente  PLoginC = new LoginCliente();
        PLoginC.setSize(400, 250); //Dimencional a JPanel para o tamanho desejado
        PLoginC.setLocation(0, 0);
        
        jPanelLogin.removeAll();
        jPanelLogin.add(PLoginC, BorderLayout.CENTER);
        jPanelLogin.revalidate();
    }//GEN-LAST:event_btn_EntrarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_EntrarCliente;
    private javax.swing.JButton btn_EntrarGerente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelLogin;
    private javax.swing.JLabel txtLogin;
    // End of variables declaration//GEN-END:variables
}
