/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.LocadoraVeiculo.TabelaVeiculos;

import java.awt.Color;
import java.awt.event.KeyEvent;

/**
 *
 * @author edunativa
 */
public class Tela_Categorias extends javax.swing.JInternalFrame {

    /**
     * Creates new form Tela_Categoria_A
     */
    public Tela_Categorias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    public void mostrarElementosInterface() {
        jPanelFichaTecnica.setVisible(true);
        jLDescricao1.setVisible(true);
        QntDias.setVisible(true);
        ValorDiaria.setVisible(true);
        Total.setVisible(true);
        jSpinnerQntDias.setVisible(true);
        jLabel5.setVisible(true);
        jLabel6.setVisible(true);
        jTextFieldVlrDiaria.setVisible(true);
        jLbResultado.setVisible(true);
    }

    public void ocultarElementosInterface() {
        jPanelFichaTecnica.setVisible(false);
        jLDescricao1.setVisible(false);
        QntDias.setVisible(false);
        ValorDiaria.setVisible(false);
        Total.setVisible(false);
        jSpinnerQntDias.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jTextFieldVlrDiaria.setVisible(false);
        jLbResultado.setVisible(false);
    }


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelCategorias = new javax.swing.JTabbedPane();
        PainelCatA = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanelFichaTecnica = new javax.swing.JPanel();
        jLDescricao1 = new javax.swing.JLabel();
        QntDias = new javax.swing.JLabel();
        jSpinnerQntDias = new javax.swing.JSpinner();
        jTextFieldVlrDiaria = new javax.swing.JTextField();
        ValorDiaria = new javax.swing.JLabel();
        Total = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLbResultado = new javax.swing.JLabel();
        bntCalcular = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jgbFichaTecnica = new javax.swing.JToggleButton();
        jgbLocar = new javax.swing.JToggleButton();
        jLSituacao = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLSituacao1 = new javax.swing.JLabel();
        jgbFichaTecnica1 = new javax.swing.JToggleButton();
        jgbLocar1 = new javax.swing.JToggleButton();
        jPanelFichaTecnica1 = new javax.swing.JPanel();
        jLDescricao2 = new javax.swing.JLabel();
        QntDias1 = new javax.swing.JLabel();
        jSpinnerQntDias1 = new javax.swing.JSpinner();
        jTextFieldVlrDiaria1 = new javax.swing.JTextField();
        ValorDiaria1 = new javax.swing.JLabel();
        Total1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLbResultado1 = new javax.swing.JLabel();
        bntCalcular1 = new javax.swing.JButton();
        PainelCatB = new javax.swing.JTabbedPane();
        PainelCatC = new javax.swing.JTabbedPane();
        PainelCatD = new javax.swing.JTabbedPane();
        PainelCatE = new javax.swing.JTabbedPane();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setClosable(true);
        setTitle("Tabela de Veículos");
        setMaximumSize(new java.awt.Dimension(800, 700));
        setPreferredSize(new java.awt.Dimension(800, 700));

        jScrollPane1.setAutoscrolls(true);

        jPanelFichaTecnica.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLDescricao1.setText("<html>  <p  text-align=”justify” style=”width:300px;”>  <b>VW Gol 2017 Highline 1.6</b>,  sensor de estacionamento traseiro; luzes de leitura dianteiras e traseiras; chave tipo canivete com comando remoto; coluna de direção com ajuste de altura e profundidade; espelhos retrovisores externos elétricos. </p>  </html>");
        jLDescricao1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        QntDias.setText("Quant. Dias");

        jSpinnerQntDias.setModel(new javax.swing.SpinnerNumberModel(1, 1, 20, 1));
        jSpinnerQntDias.setFocusable(false);

        jTextFieldVlrDiaria.setEditable(false);
        jTextFieldVlrDiaria.setText("75.00");

        ValorDiaria.setText("Valor Diária");

        Total.setText("Total");

        jLabel5.setText("R$");

        jLabel6.setText("R$");

        jLbResultado.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLbResultado.setForeground(new java.awt.Color(204, 51, 0));
        jLbResultado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLbResultado.setText("0");

        bntCalcular.setText("Calcular");
        bntCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFichaTecnicaLayout = new javax.swing.GroupLayout(jPanelFichaTecnica);
        jPanelFichaTecnica.setLayout(jPanelFichaTecnicaLayout);
        jPanelFichaTecnicaLayout.setHorizontalGroup(
            jPanelFichaTecnicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFichaTecnicaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFichaTecnicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelFichaTecnicaLayout.createSequentialGroup()
                        .addGroup(jPanelFichaTecnicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(QntDias)
                            .addComponent(jSpinnerQntDias, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanelFichaTecnicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ValorDiaria)
                            .addGroup(jPanelFichaTecnicaLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldVlrDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelFichaTecnicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Total)
                            .addGroup(jPanelFichaTecnicaLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLbResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelFichaTecnicaLayout.createSequentialGroup()
                        .addComponent(bntCalcular)
                        .addGap(103, 103, 103)))
                .addGap(14, 14, 14))
            .addGroup(jPanelFichaTecnicaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLDescricao1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanelFichaTecnicaLayout.setVerticalGroup(
            jPanelFichaTecnicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFichaTecnicaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLDescricao1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelFichaTecnicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QntDias)
                    .addComponent(ValorDiaria)
                    .addComponent(Total))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFichaTecnicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerQntDias, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldVlrDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLbResultado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bntCalcular)
                .addGap(12, 12, 12))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/LocadoraVeiculo/Imagens/Gol G7.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jgbFichaTecnica.setText("Ficha Técnica");
        jgbFichaTecnica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jgbFichaTecnicaActionPerformed(evt);
            }
        });

        jgbLocar.setText("Locar");

        jLSituacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLSituacao.setText("Disponivel");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/LocadoraVeiculo/Imagens/mobil.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLSituacao1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLSituacao1.setText("Disponivel");

        jgbFichaTecnica1.setText("Ficha Técnica");
        jgbFichaTecnica1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jgbFichaTecnica1ActionPerformed(evt);
            }
        });

        jgbLocar1.setText("Locar");

        jPanelFichaTecnica1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLDescricao2.setText("<html>  <p  text-align=”justify” style=”width:300px;”>  <b>VW Gol 2017 Highline 1.6</b>,  sensor de estacionamento traseiro; luzes de leitura dianteiras e traseiras; chave tipo canivete com comando remoto; coluna de direção com ajuste de altura e profundidade; espelhos retrovisores externos elétricos. </p>  </html>");
        jLDescricao2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        QntDias1.setText("Quant. Dias");

        jSpinnerQntDias1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 20, 1));
        jSpinnerQntDias1.setFocusable(false);

        jTextFieldVlrDiaria1.setEditable(false);
        jTextFieldVlrDiaria1.setText("75.00");

        ValorDiaria1.setText("Valor Diária");

        Total1.setText("Total");

        jLabel7.setText("R$");

        jLabel8.setText("R$");

        jLbResultado1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLbResultado1.setForeground(new java.awt.Color(204, 51, 0));
        jLbResultado1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLbResultado1.setText("0");

        bntCalcular1.setText("Calcular");
        bntCalcular1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCalcular1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFichaTecnica1Layout = new javax.swing.GroupLayout(jPanelFichaTecnica1);
        jPanelFichaTecnica1.setLayout(jPanelFichaTecnica1Layout);
        jPanelFichaTecnica1Layout.setHorizontalGroup(
            jPanelFichaTecnica1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFichaTecnica1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFichaTecnica1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelFichaTecnica1Layout.createSequentialGroup()
                        .addGroup(jPanelFichaTecnica1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(QntDias1)
                            .addComponent(jSpinnerQntDias1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanelFichaTecnica1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ValorDiaria1)
                            .addGroup(jPanelFichaTecnica1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldVlrDiaria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelFichaTecnica1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Total1)
                            .addGroup(jPanelFichaTecnica1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLbResultado1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelFichaTecnica1Layout.createSequentialGroup()
                        .addComponent(bntCalcular1)
                        .addGap(103, 103, 103)))
                .addGap(14, 14, 14))
            .addGroup(jPanelFichaTecnica1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLDescricao2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanelFichaTecnica1Layout.setVerticalGroup(
            jPanelFichaTecnica1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFichaTecnica1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLDescricao2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelFichaTecnica1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QntDias1)
                    .addComponent(ValorDiaria1)
                    .addComponent(Total1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFichaTecnica1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerQntDias1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldVlrDiaria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLbResultado1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bntCalcular1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelFichaTecnica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jgbFichaTecnica)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jgbLocar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPanelFichaTecnica1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jLSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jgbFichaTecnica1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jgbLocar1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jLSituacao1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelFichaTecnica, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jLSituacao)
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jgbFichaTecnica, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                            .addComponent(jgbLocar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelFichaTecnica1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jLSituacao1)
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jgbFichaTecnica1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jgbLocar1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(15, 15, 15))
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        PainelCatA.addTab("Tabela A", jPanel1);

        PainelCategorias.addTab("Categoria A", PainelCatA);
        PainelCategorias.addTab("Categoria B", PainelCatB);
        PainelCategorias.addTab("Categoria C", PainelCatC);
        PainelCategorias.addTab("Categoria D", PainelCatD);
        PainelCategorias.addTab("Categoria E", PainelCatE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelCategorias)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelCategorias, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
        );

        setBounds(0, 0, 706, 362);
    }// </editor-fold>//GEN-END:initComponents

    private void jgbFichaTecnicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jgbFichaTecnicaActionPerformed
       ocultarElementosInterface();
        
        if (jgbFichaTecnica.isSelected()) { //Se o Botão for selecionado faça
            jgbFichaTecnica.setBackground(Color.GREEN); // Modar a Cor do Botão
            mostrarElementosInterface(); // Mostra os Elemento da Painel
        } else {
            jgbFichaTecnica.setBackground(Color.RED); //Muda a Cor do Botão
            ocultarElementosInterface(); //Oculta os Elementos do Painel;
        }
    }//GEN-LAST:event_jgbFichaTecnicaActionPerformed

    private void bntCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCalcularActionPerformed
        int qnt = Integer.parseInt(jSpinnerQntDias.getValue().toString());
        float valor = Float.parseFloat(jTextFieldVlrDiaria.getText());
        float total = qnt * valor;
        jLbResultado.setText(String.format("%.2f", total));
    }//GEN-LAST:event_bntCalcularActionPerformed

    private void jgbFichaTecnica1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jgbFichaTecnica1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jgbFichaTecnica1ActionPerformed

    private void bntCalcular1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCalcular1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntCalcular1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane PainelCatA;
    private javax.swing.JTabbedPane PainelCatB;
    private javax.swing.JTabbedPane PainelCatC;
    private javax.swing.JTabbedPane PainelCatD;
    private javax.swing.JTabbedPane PainelCatE;
    private javax.swing.JTabbedPane PainelCategorias;
    private javax.swing.JLabel QntDias;
    private javax.swing.JLabel QntDias1;
    private javax.swing.JLabel Total;
    private javax.swing.JLabel Total1;
    private javax.swing.JLabel ValorDiaria;
    private javax.swing.JLabel ValorDiaria1;
    private javax.swing.JButton bntCalcular;
    private javax.swing.JButton bntCalcular1;
    private javax.swing.JLabel jLDescricao1;
    private javax.swing.JLabel jLDescricao2;
    private javax.swing.JLabel jLSituacao;
    private javax.swing.JLabel jLSituacao1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLbResultado;
    private javax.swing.JLabel jLbResultado1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelFichaTecnica;
    private javax.swing.JPanel jPanelFichaTecnica1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerQntDias;
    private javax.swing.JSpinner jSpinnerQntDias1;
    private javax.swing.JTextField jTextFieldVlrDiaria;
    private javax.swing.JTextField jTextFieldVlrDiaria1;
    private javax.swing.JToggleButton jgbFichaTecnica;
    private javax.swing.JToggleButton jgbFichaTecnica1;
    private javax.swing.JToggleButton jgbLocar;
    private javax.swing.JToggleButton jgbLocar1;
    // End of variables declaration//GEN-END:variables
}
